import numpy as np
import torch

HUMAN_ENCODE_OFFSET = [0,0,0,1]*21
HUMAN_DECODE_OFFSET = list(HUMAN_ENCODE_OFFSET)
HUMAN_ENCODE_SCALE = [0.2, 0.2, 0.2, 0.02]*21
HUMAN_DECODE_SCALE = list(HUMAN_ENCODE_SCALE)

ROBOT_ENCODE_OFFSET = [0., 0.9, -1.8]*4
ROBOT_DECODE_OFFSET = list(ROBOT_ENCODE_OFFSET)

HUMAN_CONFIG_DIM = 84
ROBOT_CONFIG_DIM = 12

HUMAN_ARM_LENGTH = 0.506
HUMAN_LEG_LENGTH = 0.92
ROB_HEIGHT = 0.32

